### PR TITLE
fix(devops): used fixed branch to create release, and never delete it from git

### PR DESCRIPTION
**Pull request by cnlangzi**
## Fixes
- fixed https://github.com/herumi/bls-go-binary/issues/20

## Demo
- https://github.com/0chain/gosdk/actions/runs/5110621860/jobs/9186713576 . it is built from the fork https://github.com/cnlangzi/bls-go-binary/releases/tag/v1.30.4

### CODE REVIEW

**Comment by herumi** [comment]
Sorry for the late reply. Thanks for the patch. I will check it out.

**Comment by cnlangzi** [comment]
> Sorry for the late reply. Thanks for the patch. I will check it out.

don't merge it now. let me fix linux/arm issue first. https://github.com/herumi/bls-go-binary/issues/24

**Comment by lcswillems** [comment]
@cnlangzi Do you think it should be relatively easy to fix #24 ?

I would need this to be fixed in order to be able to compile my lib for darwin/arm64

**Comment by cnlangzi** [comment]
> @cnlangzi Do you think it should be relatively easy to fix #24 ?
> 
> I would need this to be fixed in order to be able to compile my lib for darwin/arm64

please use my fork to fix it as a workaround first. I will fix arm64 issue in this PR.

```
replace github.com/herumi/bls-go-binary => github.com/cnlangzi/bls-go-binary v1.30.7
```

**Comment by herumi** [comment]
This patch fails at "Create branch" at my test-bls-go-binary.
https://github.com/herumi/test-bls-go-binary/actions/runs/5186125201/jobs/9346834393#step:3:47
Do you think it's necessary something to set up?

**Comment by cnlangzi** [comment]
> This patch fails at "Create branch" at my test-bls-go-binary. https://github.com/herumi/test-bls-go-binary/actions/runs/5186125201/jobs/9346834393#step:3:47 Do you think it's necessary something to set up?

delete `release` on remote git first. and never update it manually.
```
Already up to date.
fatal: refusing to merge unrelated histories
```

**Comment by herumi** [comment]
>used fixed branch to create release, and never delete it from git

It runs well if I removed a release tag. But the next time I tried it, I got the same error.
Should I merge the generated release branch into the main?

**Comment by cnlangzi** [comment]
@herumi  in general, it should be released from master only.

**Comment by herumi** [comment]
The latest [release.yml](https://github.com/herumi/test-bls-go-binary/commit/c362a705703a4d909e029f8d4d5f89f1395cdd90) of test-bls-go-binary seems to be able to build both amd64 and arm64 darwin binary.
- https://github.com/herumi/test-bls-go-binary/actions/runs/5186814211/jobs/9348461372#step:4:122
- https://github.com/herumi/test-bls-go-binary/actions/runs/5186814211/jobs/9348461372#step:4:122

**Comment by cnlangzi** [comment]
> The latest [release.yml](https://github.com/herumi/test-bls-go-binary/commit/c362a705703a4d909e029f8d4d5f89f1395cdd90) of test-bls-go-binary seems to be able to build both amd64 and arm64 darwin binary.
> 
> * https://github.com/herumi/test-bls-go-binary/actions/runs/5186814211/jobs/9348461372#step:4:122
> * https://github.com/herumi/test-bls-go-binary/actions/runs/5186814211/jobs/9348461372#step:4:122

Good job. could you merge it on master first?  I can update my fork, and verify it on our projects again.

**Comment by herumi** [comment]
Thank you for the patch. I've merged it.

**Comment by herumi** [comment]
> delete `release` on remote git first. and never update it manually.

I don't understand your release.yml spec yet.
First, I remove a release branch on the remote, which runs well.
Next, when I run the release.yml after I updated the master branch, is it necessary to remove the new release branch created by release.yml .
If I don't remove it, it [failed](https://github.com/herumi/bls-go-binary/actions/runs/5206430280/jobs/9392989254).

**Comment by cnlangzi** [comment]
@herumi  let me explain it

1.  pull latest code, switch or create `release`:           
```
     git pull 
     git checkout release 2>/dev/null || git checkout -b release
````
2. merge latest changes from master. 
```
git merge origin/master -q -m "chore(git): merged latest master"
``` 
3. because we always create  new release from `release` branch. so latest changes should be merged into current `release` branch 
```
      - name: Create Release
        id: create_release
        run: gh release create "${{ github.event.inputs.version }}" -t "${{ github.event.inputs.version }}" --target "release" --latest
```

if it fails on `git merge origin/master -q -m "chore(git): merged latest master"`, it means your `release` was created from other branch instead of `maser`.  NB: new version should always be released from `master`. 

I think `workflow_dispatch` is missed on the `release.yml`. let me fix it now.

**Comment by cnlangzi** [comment]
```
branch 'release' set up to track 'origin/release'.
fatal: refusing to merge unrelated histories
```

your `release` has some issues. 
Screenshot 2023-06-08 at 11 05 50

**Comment by cnlangzi** [comment]
Screenshot 2023-06-08 at 11 08 15

**Comment by cnlangzi** [comment]
for now, you can just do it like 
- delete `release` branch from remote
- create new version from master branch on 

in next release, just do it like
- merge changes into master
- create new version from master branch again on https://github.com/herumi/bls-go-binary/actions/workflows/release.yml


and `create branch` job always merge latest changes from master into `release`, and create new version from latest codebase.

**Comment by cnlangzi** [comment]
@herumi  I think I know what happens there. it is broken by submodule https://github.com/cnlangzi/bls-go-binary/tree/master/src

`make command` make some changes on submodule repos, we can't push it. let me try it.

**Comment by cnlangzi** [comment]
@herumi  try https://github.com/herumi/bls-go-binary/pull/27

**Comment by herumi** [comment]
> for now, you can just do it like
> 
>     * delete `release` branch from remote
> 
>     * create new version from master branch on
> 
> 
> in next release, just do it like
> 
>     * merge changes into master
> 
>     * create new version from master branch again on

I've merged #27 and set tag v2.1.2 and run release.yml with v2.1.2, then
```
* <cff34fc> 2023-06-08 [github-actions]  (origin/release)  fix(release): added libs for windows
* <aad2660> 2023-06-08 [github-actions]   fix(release): added libs for ios/ios simulator
* <5f2174c> 2023-06-08 [github-actions]   fix(release): added libs for darwin
* <fce82d5> 2023-06-08 [github-actions]   fix(release): added libs for android
* <2d62ad6> 2023-06-08 [github-actions]   fix(release): added libs for linux(amd64/arm64)
*   <d90e514> 2023-06-08 [MITSUNARI Shigeo]  (HEAD -> master, tag: v2.1.2, origin/master, origin/HEAD)  Merge pull request #27 from cnlangzi/fix/clean_submodule
```

Sorry for the elementary question.

>     * create new version from master branch on

Does it mean creating a branch named v2.1.2, not a tag?

>     * merge changes into master

Does it mean merging the above `origin/release` into master?

**Comment by cnlangzi** [comment]
> Does it mean creating a branch named v2.1.2, not a tag?
no, just trigger workflow with `v2.1.2` from https://github.com/herumi/bls-go-binary/actions/workflows/release.yml, everything will be done automatically. 

> Does it mean merging the above origin/release into master?
No, we never merge origin/release into master. Because you don't push those binaries(bls/lib) on `master`.

so don't create tag manually, it will be created automatically by latest job `create release`. just ignore release branch, and work as normal. trigger workflow if you want to release a new version

**Comment by cnlangzi** [comment]
BTW: it is a workaroud to merge master into release manually to fix any conflicts.

**Comment by herumi** [comment]
Thanks for the detailed explanation.
I tested it on [test-bls-go-binary](https://github.com/herumi/test-bls-go-bianry) with [minimized release.yml](https://github.com/herumi/test-bls-go-binary/blob/master/.github/workflows/min-release.yml).

- `git push origin --delete release`
  - I've removed release branch.
-  I run release.yml with v2.3.1 (I don't make a tag), and it runs well.
- `git pull`
```
From github.com:herumi/test-bls-go-binary
 * [new branch]      release    -> origin/release
 * [new tag]         v2.3.1     -> v2.3.1
```
- I modified master branch a little, and commit it.
- I run release.yml with v2.3.2, [it fails](https://github.com/herumi/test-bls-go-binary/actions/runs/5209042363/jobs/9398369784).

image

Then, I run the followings:

```
git checkout -b release
git reset --hard origin/release
git merge origin/master
git push origin release
```
And I run release.yml with v2.3.2 again, and it runs well.
Is it a correct process?

**Comment by cnlangzi** [comment]
@herumi yes. maybe `reset --hard origin/release` is better to clean local git status.

**Comment by herumi** [comment]
Thank you. I understood.
It would be nice if it would automatically merge at the beginning of release.yml.

**Pull request merged**
