### PR TITLE
Update linux/amd64 binaries and add linux/arm64

### PR DESCRIPTION
**Pull request by traian-schiau**

### CODE REVIEW

**Comment by herumi** [comment]
I added linux/arm64 binary. Could you try it?

**Comment by traian-schiau** [comment]
Hi, we could try to do some tests on today (EET),  but it will help if the linux/amd64 lib is also updated and maybe create a version tag so we could reference better the package in go.mod.

**Comment by herumi** [comment]
I added v1.0 tag.

**Comment by traian-schiau** [comment]
All looks good for us, thanks. Just one note, the version tag should contain a patch level as well, so it should be v1.0.0 (instead of v1.0).

**Comment by herumi** [comment]
Okay, I've added the tag.

**Pull request closed without merging**
